### ISSUE TITLE
Security alert on FlagQualifier 

### ISSUE THREAD

**Issue by luancma** [cloudinary/js-transformation-builder-sdk#31]
After implement cloudnary sdk, our CodeQL complained about the class FlagQualifier inside this package.

Path of the issue:
src/qualifiers/flag/FlagQ

<img width="931" alt="Screenshot 2023-08-30 at 16 09 38" src="https://github.com/cloudinary/js-transformation-builder-sdk/assets/17798410/7c954861-07c0-4470-8cba-1f2549c9a08e">
ualifier.ts - Line 23

**Comment by PixelCook** [comment]
Thank you for providing that information, we are looking into this and will update you soon.
