### ISSUE TITLE
types/types.js import is incorrect in IEffectActionModel.ts

### ISSUE THREAD

**Issue by kapoor-rakshit** [cloudinary/js-transformation-builder-sdk#58]
In IEffectActionModel.ts, import of { ExtractModeType } from "types/types.js" in incorrect.
It should have been a relative path i.e. "../../types/types.js"; and **not** absolute path.

As a result library is unable to build. Attached screenshot herein.

![image](https://github.com/user-attachments/assets/f9c08b51-0365-46d8-b28c-f1ff141cc545)

**Comment by kapoor-rakshit** [comment]
@magdakwiecien @mckomo-cl 
Please have a look at this Issue and related PR.

**Comment by alsoicode** [comment]
This issue is currently blocking development for me. What version can I roll back to until this fix is released?

**Comment by kapoor-rakshit** [comment]
> This issue is currently blocking development for me. What version can I roll back to until this fix is released?

@cloudinary/transformation-builder-sdk **v1.15.0** is having bug, so anything other than it will work.

A snippet from my **yarn.lock**
"@cloudinary/html@^1.13.0":
  version "1.13.0"

"@cloudinary/ng@^2.0.2":
  version "2.0.2"

"@cloudinary/transformation-builder-sdk@^1.13.0":
  version "1.13.3"

"@cloudinary/url-gen@^1.16.1", "@cloudinary/url-gen@^1.7.0":
  version "1.19.0"

**Comment by lisa-kuzmina** [comment]
Hi. The fix is deployed, version 1.15.1. Please let us know if the issue is resolved @kapoor-rakshit @alsoicode

**Comment by kapoor-rakshit** [comment]
> Hi. The fix is deployed, version 1.15.1. Please let us know if the issue is resolved @kapoor-rakshit @alsoicode

Yes, it is fixed.
Thanks.

**Comment by alsoicode** [comment]
Thanks for the fix, but one of the other modules: @cloudinary/ng or @cloudinary/url-gen is still pointing at the previous version. I had to install the transformation-builder-sdk as well in order for it to use that specific package versus what's installed by the modules mentioned in the quick start.

**Comment by magdakwiecien** [comment]
@alsoicode Are you sure you've fully reinstalled dependencies in your project and it's not a cached version? 
(Removing `node_modules` and installing them again might help). 

The `@cloudinary/url-gen` has `@cloudinary/transformation-builder-sdk` as an internal dependency, [but its version is specified with a caret](https://github.com/cloudinary/js-url-gen/blob/master/package.json#L153) (`^`), so it should install the newest version of this dependency every time when you install `@cloudinary/url-gen`.
